language: cpp

compiler:
  - gcc
  - clang

notifications:
        email: false
        irc:
                channels:
                        - "irc.rizon.net#gtorrent"
                on_success: always
                on_failure: always
        template:
                - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
                - "Change view : %{compare_url}"
                - "Build details: %{build_url}"
                - "Result: %{result}"

cache: apt

before_install:
        # Debugging
        - lsb_release -sc
        # Update repositories to not be shit.
        - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe"
        # gtk 3.12 | oh god I have no idea what im doing
        - yes "" | sudo add-apt-repository "deb http://ppa.launchpad.net/gnome3-team/gnome3-staging/ubuntu/ trusty main"
        - sudo apt-get clean
        - sudo apt-get update
        # Update dependancies
        #- scripts/deps.sh


install:
        # Install dependancies
        - sudo apt-get install -f -y --force-yes libboost-all-dev libncurses5-dev
        # Update g++ to 4.8
        - sudo apt-get install -f -y g++
        - sudo apt-get install -f -y clang
        - wget http://a.pomf.se/eyueqb.tar.xz
        - sudo tar -C /usr -xJvf eyueqb.tar.xz

script:
        - mkdir -p build/
        - cd build/
        - cmake ..
        - make -j2
